// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY'),
    appId: '1:270329171884:web:c57c788674006f05077409',
    messagingSenderId: '270329171884',
    projectId: 'form-f8d39',
    authDomain: 'form-f8d39.firebaseapp.com',
    storageBucket: 'form-f8d39.firebasestorage.app',
    measurementId: 'G-TJJ4ECBNMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_API_KEY'),
    appId: '1:270329171884:android:61ff6cc8574f0001077409',
    messagingSenderId: '270329171884',
    projectId: 'form-f8d39',
    storageBucket: 'form-f8d39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY'),
    appId: '1:270329171884:ios:ec2548445ab1ffc2077409',
    messagingSenderId: '270329171884',
    projectId: 'form-f8d39',
    storageBucket: 'form-f8d39.firebasestorage.app',
    iosBundleId: 'com.example.monFormulaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY'),
    appId: '1:270329171884:ios:ec2548445ab1ffc2077409',
    messagingSenderId: '270329171884',
    projectId: 'form-f8d39',
    storageBucket: 'form-f8d39.firebasestorage.app',
    iosBundleId: 'com.example.monFormulaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY'),
    appId: '1:270329171884:web:8f5cb7789d820b02077409',
    messagingSenderId: '270329171884',
    projectId: 'form-f8d39',
    authDomain: 'form-f8d39.firebaseapp.com',
    storageBucket: 'form-f8d39.firebasestorage.app',
    measurementId: 'G-0JWKX5JJ0E',
  );
}
